version: '3'
services:
  site:
    image : "totocastaldi/personal-finance-site:${TAG}"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - /config/config-fe.json:/data/www/config.json
  api:
    image : "totocastaldi/personal-finance-api:${TAG}"
    ports:
      - "5000:5000"
    links:
      - postgresql
    depends_on:
      - postgresql-liquibase
    environment:
      - LOG_LEVEL=DEBUG
      - LOG_FILE_NAME=api
    volumes:
      - /var/lib/buddy/log:/app/log
      - /var/lib/buddy/upload:/upload
      - /var/lib/buddy/config/config-be.json:/app/common/config.json
  batch:
    image : "totocastaldi/personal-finance-batch:${TAG}"
    links:
      - postgresql
    depends_on:
      - postgresql-liquibase
    environment:
      - LOG_LEVEL=DEBUG
      - LOG_FILE_NAME=batch
    volumes:
      - /var/lib/buddy/log:/app/log
      - /var/lib/buddy/config/config-be.json:/app/common/config.json
  postgresql:
    image: postgres:11.5
    volumes:
      - personal-finance-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dbpsql
      - POSTGRES_USER=dbpsql
      - POSTGRES_DB=dbpsql
  postgresql-liquibase:
    image: totocastaldi/personal-finance-liquibase:${TAG}
    environment:
      - LIQUIBASE_URL=jdbc:postgresql://postgresql/dbpsql
      - LIQUIBASE_USERNAME=dbpsql
      - LIQUIBASE_PASSWORD=dbpsql
    links:
      - postgresql
    depends_on:
      - postgresql

volumes:
  personal-finance-postgres:
