version: '3'
services:
  batch:
    image : "totocastaldi/personal-finance-batch:${TAG}"
    links:
      - postgresql
    depends_on:
      - postgresql-liquibase
    volumes:
      - /var/lib/buddy/log:/app/log
  postgresql:
    image: postgres:11.5
    volumes:
      - personal-finance-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dbpsql
      - POSTGRES_USER=dbpsql
      - POSTGRES_DB=dbpsql
  postgresql-liquibase:
    image: totocastaldi/personal-finance-liquibase:${TAG}
    environment:
      - LIQUIBASE_URL=jdbc:postgresql://postgresql/dbpsql
      - LIQUIBASE_USERNAME=dbpsql
      - LIQUIBASE_PASSWORD=dbpsql
    links:
      - postgresql
    depends_on:
      - postgresql

volumes:
  personal-finance-postgres:
